package dailyByte;

/*You are given two strings, s and t which only consist of lowercase letters. t is
generated by shuffling the letters in s as well as potentially adding an additional
random character. Return the letter that was randomly added to t if it exists,
otherwise, return ’ ‘.
Note: You may assume that at most one additional character can be added to t.
Ex: Given the following strings...
s = "foobar", t = "barfoot", return 't'
s = "ide", t = "idea", return 'a'
s = "coding", t "ingcod", return ''
*/

import java.util.Arrays;

public class spotTheDifference {
    public static void main(String[] args) {
        String s = "a";
        String t = "aa";
        char ch = spotDiff(s,t);
        System.out.println(ch);
    }

    private static char spotDiff(String s, String t) {
//        int[] arr = new int[26];
//        // add strings from s
//        for (int i=0;i<s.length();i++)
//            arr[s.charAt(i)-'a']++;
//
//        // remove strings from t
//        for (int j=0;j<t.length();j++)
//            arr[t.charAt(j)-'a']--;
//
//        // check if arr is zero or not
//        for (int i=0;i<26;i++){
//            if (arr[i]!=0)
//                return (char)(i+'a');
//        }
//          return 0;

        char result = 0;
        for (char ch:s.toCharArray())
            result ^= ch;

        for (char ch:t.toCharArray())
            result ^=ch;

        return result;
    }
}